source 'https://rubygems.org'

ruby '2.2.3'

gem 'sinatra'
gem 'thin'
gem 'dotenv'
gem 'slack-notifier'
gem 'poseidon'
gem 'snappy'
gem 'foreman'

group :development do
  gem 'guard'
  gem 'guard-minitest'
  gem 'pry'
end
